"""

Revision ID: 47d6db5e17bd
Revises: 519fad0badb6
Create Date: 2023-07-18 21:05:47.769296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6db5e17bd'
down_revision = '519fad0badb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
