"""Initial check

Revision ID: 519fad0badb6
Revises: 
Create Date: 2023-07-18 21:00:06.821577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519fad0badb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
